package model.enums.commands;

public enum GameMenuCommand implements Command {
    GAME_NEW_PATTERN("^\\s*game\\s+new\\s+-u\\s+(?<usernames>(\\w+\\s*){1,3})\\s*$"),
    MAP_SELECT_PATTERN("^\\s*game\\s+map\\s+(?<number>\\d+)\\s*$"),
    CHOOSE_MAP("^\\s*game\\s+map\\s+(?<mapId>\\d+)\\s*$"),
    LOAD_GAME("^\\s*load\\s+game\\s*$"),
    EXIT_GAME("^\\s*exit\\s+game\\s*$"),
    TERMINATE_GAME("^\\s*terminate\\s+game\\s*$"),
    CHANGE_TURN("^\\s*next\\s+turn\\s*$"),
    SHOW_TIME("^\\s*time\\s*$"),
    SHOW_DATE("^\\s*date\\s*$"),
    SHOW_DATE_AND_TIME("^\\s*datetime\\s*$"),
    SHOW_WEEKDAY("^\\s*day\\s+of\\s+the\\s+week\\s*$"),
    CHEAT_ADVANCE_TIME("^\\s*cheat\\s+advance\\s+time\\s+(?<number>\\d+)h\\s*$"),
    CHEAT_ADVANCE_DATE("^\\s*cheat\\s+advance\\s+date\\s+(?<number>\\d+)d\\s*$"),
    SHOW_SEASON("^\\s*season\\s*$"),
    CHEAT_CREATE_THUNDER("^\\s*cheat\\s+Thor\\s+-l(?<X>\\d+)\\s+(?<Y>\\d+)\\s*$"),
    SHOW_WEATHER("^\\s*weather\\s*$"),
    FORECAST_WEATHER("^\\s*weather\\s+forecast\\s*$"),
    CHEAT_CHANGE_WEATHER("^\\s*cheat\\s+set\\s+weather\\s+(?<weather>\\S+)\\s*$"),
    BUILD_GREENHOUSE("^\\s*greenhouse\\s+build\\s*$"),
    CHOOSE_FARM("^\\s*choose\\s+farm\\s+-u(?<username>\\S+)\\s+-f(?<farmId>\\d+)\\s*$"),
    WALK("^\\s*walk\\s+-l\\s+(?<X>\\d+)\\s+(?<Y>\\d+)\\s*$"),
    PRINT_MAP("^\\s*print\\s+map\\s+-l\\s+(?<X>\\d+)\\s+(?<Y>\\d+)\\s+-s\\s+(?<size>\\d+)\\s*$"),
    SHOW_LEGEND("^\\s*help\\s+reading\\s+map\\s*$"),
    SHOW_ENERGY("^\\s*energy\\s+show\\s*$"),
    CHEAT_CHANGE_ENERGY("^\\s*energy\\s+set\\-v\\s+(?<value>\\d+)\\s*$"),
    UNLIMITED_ENERGY("^\\s*energy\\s+unlimited\\s*$"),
    SHOW_INVENTORY("^\\s*inventory\\s+show\\s*$"),
    DISCARD_ITEM("^\\s*inventory\\s+trash\\s+-i\\s+(?<itemname>\\S+)(?:\\s+-n\\s+(?<number>\\d+))?\\s*$"),
    EQUIP_TOOL("^\\s*tools\\s+equip\\s+(?<toolname>\\S+)\\s*$"),
    SHOW_CURRENT_TOOL("^\\s*tools\\s+show\\s+current\\s*$"),
    SHOW_AVAILABLE_TOOLS("^\\s*tools\\s+show\\s+available\\s*$"),
    UPGRADE_TOOL("^\\s*tools\\s+upgrade\\s+(?<toolname>\\S+)\\s*$"),
    USE_TOOL("^\\s*tools\\s+use\\s+-d\\s+(?<direction>\\S+)\\s*$"),
    SHOW_CRAFT_INFO("^\\s*craftinfo\\s+-n\\s+(?<craft-name>\\S+)\\s*$"),
    PLANT_SEED("^\\s*plant\\s+-s\\s+(?<seed>\\S+)\\s+-d\\s+(?<direction>\\d)\\s*$"),
    SHOW_PLANT("^\\s*showplant\\s+-l\\s+(?<X>\\d+)\\s+(?<Y>\\d+)\\s*$"),
    FERTILIZE("^\\s*fertilize\\s+-f\\s+(?<fertilizer>\\S+)\\s+(?<direction>\\d)\\s*$"),
    SHOW_WATER_LEFT("^\\s*how\\s*much\\s+water\\s*$"),
    FISH("^\\s*fishing\\s+-p\\s+(?<fishingPole>\\S+)\\s*$"),
    USE_ARTISAN("^\\s*artisan\\s+use\\s+(?<artisan>\\S+)\\s+(?<item>\\S+)\\s*$"),
    GET_ARTISAN("^\\s*artisan\\s+get\\s+(?<artisan>\\S+)\\s*$"),
    SHOW_TALK_HISTORY("^\\s*talk\\s+history\\s+-u\\s+(?<username>\\S+)\\s*$"),
    GIFT("^\\s*Gift\\s+-u\\s+(?<username>\\S+)\\s+-i\\s+(?<item>\\S+)\\s+-a\\s+(?<amount>\\d+)\\s*$"),
    SHOW_GIFTS("^\\s*Gift\\s+list\\s*$"),
    RATE_GIFT("^\\s*Gift\\s+rate\\s+-i\\s+(?<giftNumber>\\d+)\\s+-r\\s+(?<rate>\\d)\\s*$"),
    SHOW_GIFT_HISTORY("^\\s*Gift\\s+history\\s+-u\\s+(?<username>\\S+)\\s*$"),
    HUG("^\\s*hug\\s+-u\\s+(?<username>\\S+)\\s*$"),
    GIVE_FLOWER("^\\s*flower\\s+-u\\s+(?<username>\\S+)\\s*$"),
    ASK_MARRIAGE("^\\s*ask\\s+marriage\\s+-u\\s+(?<username>\\S+)\\s+-r\\s+(?<ring>\\S+)\\s*$"),
    RESPOND_TO_MARRIAGE("^\\s*respond\\s+(?<response>-accept|-reject)\\s+-u\\s+(?<username>\\S+)\\s*$"),
    MEET_NPC("^\\s*meet\\s+NPC\\s+(?<npcName>\\S+)\\s*$"),
    GIFT_NPC("^\\s*Gift\\s+NPC\\s+(?<npcName>\\S+)\\s+-i\\s+(?<item>\\S+)\\s*$"),
    LIST_NPC_FRIENDSHIPS("^\\s*friendship\\s+NPC\\s+list\\s*$"),
    LIST_QUESTS("^\\s*quests\\s+list\\s*$"),
    TREE_INFO("^\\s*tree\\s+info\\s+(?<name>\\S+)\\s*$"),
    CROP_INFO("^\\s*crop\\s+info\\s+(?<name>\\S+)\\s*$"),
    FORAGING_CROP_INFO("^\\s*foraging\\s+crop\\s+info\\s+(?<name>\\S+)\\s*$"),
    FORAGING_TREE_INFO("^\\s*foraging\\s+tree\\s+info\\s+(?<name>\\S+)\\s*$"),
    FRUITS_INFO("^\\s*fruit\\s+info\\s+(?<name>\\S+)\\s*$"),
    COMPLETE_QUEST("^\\s*quests\\s+finish\\s+-i\\s+(?<index>\\d+)\\s*$"),
    SELECT_PRODUCTS_AVAILABLE("^\\s*show\\s+all\\s+available\\s+products\\s*$"),
    SELECT_PRODUCTS_ALL("^\\s*show\\s+all\\s+products\\s*$"),
    SELECT_PURCHASE("^\\s*purchase\\s+(?<productName>\\S+)\\s+-n\\s+(?<count>\\S+)\\s*$"),
    SELECT_ADD_DOLLARS("^\\s*cheat\\s+add\\s+(?<count>\\S+)\\s+dollars\\s*$"),
    SELECT_FRIENDSHIPS("^\\s*friendships\\s*$"),
    SELECT_TALK("^\\s*talk\\s+-u\\s+(?<username>\\S+)\\s+-m\\s+(?<message>[A-Za-z ]+)\\s*$"),
    SELECT_TALK_HISTORY("^\\s*talk\\s+history\\s+-u\\s+(?<username>\\S+)\\s*$"),
    SELECT_GIFT("^\\s*Gift\\s+-u\\s+(?<username>\\S+)\\s+-i\\s+(?<item>\\S+)\\s+-a\\s+(?<amount>\\S+)\\s*$"),
    SELECT_LIST_GIFT("^\\s*Gift\\s+list\\s*$"),
    SELECT_RATE_GIFT("^\\s*Gift\\s+rate\\s+-i\\s+(?<giftNumber>\\S+)\\s+-r\\s+(?<rate>\\S+)\\s*$"),
    SELECT_GIFT_HISTORY("^\\s*Gift\\s+history\\s+-u\\s+(?<username>\\S+)\\s*$"),
    SELECT_HUG("^\\s*hug\\s+-u\\s+(?<username>\\S+)\\s*$"),
    SELECT_FLOWER("^\\s*flower\\s+-u\\s+(?<username>\\S+)\\s*$"),
    SELECT_MARRIAGE_ASK("^\\s*ask\\s+marriage\\s*-u\\s+(?<username>\\S+)\\s+-r\\s+(?<ring>\\S+)\\s*$"),
    SELECT_MARRIAGE_RESPOND("^\\s*respond\\s+(?<respond>(-accept|-reject))\\s+-u\\s+(?<username>\\S+)\\s*$"),
    SELECT_TRADE_START("^\\s*start\\s+trade\\s*$"),
    SELECT_TRADE("^\\s*trade\\s+-u\\s+(?<username>\\S+)\\s+-t\\s+(?<type>request|offer)\\s+(?:-i\\s+(?<item>\\S+)\\s+-a\\s+(?<amount>\\d+)\\s+)?(?:-p\\s+(?<price>\\d+\\.?\\d*))?(?:-ti\\s+(?<targetItem>\\S+)\\s+-ta\\s+(?<targetAmount>\\d+)\\s+)?\\s*$"),
    SELECT_LIST_TRADE("^\\s*trade\\s+list\\s*$"),
    SELECT_TRADE_RESPONSE("^\\s*trade\\s+respond\\s+(?<respond>(-accept|-reject))\\s+-i\\s+(?<id>\\S+)\\s*$"),
    SELECT_TRADE_HISTORY("^\\s*trade\\s+history\\s*$"),
    SELECT_SELL("^\\s*sell\\s+(?<productName>\\S+)\\s+-n\\s+(?<count>\\S+)\\s*$"),
    BUILD_BARN("^\\s*build\\s+-a\\s+(?<buildingname>[a-zA-Z ]+)\\s+-l\\s+(?<X>\\d+)\\s+(?<Y>\\d+)\\s*$"),
    BUY_ANIMAL("^\\s*buy\\s+animal\\s+-a\\s+(?<animal>\\S+)\\s+-n\\s+(?<name>\\S+)\\s*$"),
    PET_ANIMAL("^\\s*pet\\s+-n\\s+(?<name>\\S+)\\s*$"),
    CHEAT_SET_FRIENDSHIP("^\\s*cheat\\s+set\\s+friendship\\s+-n\\s+(?<name>\\S+)\\s+-c\\s+(?<amount>\\d+)\\s*$"),
    SHOW_ANIMALS("^\\s*animals\\s*$"),
    SHEPHERD_ANIMALS("^\\s*shepherd\\s+animals\\s+-n\\s+(?<name>\\S+)\\s+-l\\s+(?<X>\\d+)\\s+(?<Y>\\d+)\\s*$"),
    FEED_HAY("^\\s*feed\\s+hay\\s+-n\\s+(?<name>\\S+)\\s*$"),
    SHOW_PRODUCES("^\\s*produces\\s*$"),
    COLLECT_PRODUCE("^\\s*collect\\s+produce\\s+-n\\s+(?<name>\\S+)\\s*$"),
    SELL_ANIMAL("^\\s*sell\\s+animal\\s+-n\\s+(?<name>\\S+)\\s*$"),
    FISHING("^\\s*fishing\\s+-p\\s+(?<pole>[a-zA-Z ]+)\\s*$");

    private final String pattern;

    GameMenuCommand(String pattern) {
        this.pattern = pattern;
    }

    @Override
    public String getPattern() {
        return pattern;
    }
}
